// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoVTDSxha_E_zLcBg8o8FEAfHVYixAndE',
    appId: '1:1078955598427:web:c93e13810e5237fd29957e',
    messagingSenderId: '1078955598427',
    projectId: 'talkify-6f2b8',
    authDomain: 'talkify-6f2b8.firebaseapp.com',
    storageBucket: 'talkify-6f2b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8AZ2zCBkzeAuc443BJhLuErP3xnzw-n4',
    appId: '1:1078955598427:android:babdf997c06fcde029957e',
    messagingSenderId: '1078955598427',
    projectId: 'talkify-6f2b8',
    storageBucket: 'talkify-6f2b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRZIGCUgtSqhBNK-k33amoWkBkF0_aMNg',
    appId: '1:1078955598427:ios:99b0a0fea7ec64fd29957e',
    messagingSenderId: '1078955598427',
    projectId: 'talkify-6f2b8',
    storageBucket: 'talkify-6f2b8.appspot.com',
    iosBundleId: 'com.example.talkifyChatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRZIGCUgtSqhBNK-k33amoWkBkF0_aMNg',
    appId: '1:1078955598427:ios:69cdd444bf4dbf4729957e',
    messagingSenderId: '1078955598427',
    projectId: 'talkify-6f2b8',
    storageBucket: 'talkify-6f2b8.appspot.com',
    iosBundleId: 'com.example.talkifyChatApplication.RunnerTests',
  );
}
